from abc import ABC, abstractmethod
import chess


class Bot(ABC):
    @abstractmethod
    def get_move(self, board: chess.Board) -> str:
        """
        Returns move generated by bot in uci notation
        """
        pass
